# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'software.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 650)
        MainWindow.setMinimumSize(QtCore.QSize(900, 650))
        MainWindow.setMaximumSize(QtCore.QSize(900, 650))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 20, 901, 31))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 60, 361, 311))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 30, 61, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 30, 81, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.displayDirname = QtWidgets.QTextBrowser(self.groupBox)
        self.displayDirname.setGeometry(QtCore.QRect(130, 30, 121, 31))
        self.displayDirname.setObjectName("displayDirname")
        self.imagelabel_2 = QtWidgets.QLabel(self.groupBox)
        self.imagelabel_2.setGeometry(QtCore.QRect(40, 90, 281, 201))
        self.imagelabel_2.setFrameShape(QtWidgets.QFrame.Box)
        self.imagelabel_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.imagelabel_2.setText("")
        self.imagelabel_2.setObjectName("imagelabel_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(470, 60, 361, 311))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(50, 30, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.displayFname = QtWidgets.QTextBrowser(self.groupBox_2)
        self.displayFname.setGeometry(QtCore.QRect(140, 30, 191, 31))
        self.displayFname.setObjectName("displayFname")
        self.imagelabel = QtWidgets.QLabel(self.groupBox_2)
        self.imagelabel.setGeometry(QtCore.QRect(50, 90, 281, 201))
        self.imagelabel.setFrameShape(QtWidgets.QFrame.Box)
        self.imagelabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.imagelabel.setText("")
        self.imagelabel.setObjectName("imagelabel")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(60, 390, 361, 231))
        self.groupBox_4.setObjectName("groupBox_4")
        self.skewness = QtWidgets.QCheckBox(self.groupBox_4)
        self.skewness.setGeometry(QtCore.QRect(140, 120, 101, 21))
        self.skewness.setObjectName("skewness")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 111, 41))
        self.label_2.setObjectName("label_2")
        self.waveRate = QtWidgets.QCheckBox(self.groupBox_4)
        self.waveRate.setGeometry(QtCore.QRect(20, 120, 101, 21))
        self.waveRate.setObjectName("waveRate")
        self.CV = QtWidgets.QCheckBox(self.groupBox_4)
        self.CV.setGeometry(QtCore.QRect(250, 90, 101, 21))
        self.CV.setObjectName("CV")
        self.kurtosis = QtWidgets.QCheckBox(self.groupBox_4)
        self.kurtosis.setGeometry(QtCore.QRect(250, 120, 101, 21))
        self.kurtosis.setObjectName("kurtosis")
        self.peakPos = QtWidgets.QCheckBox(self.groupBox_4)
        self.peakPos.setGeometry(QtCore.QRect(140, 90, 101, 21))
        self.peakPos.setObjectName("peakPos")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(20, 20, 111, 41))
        self.label.setObjectName("label")
        self.algorithmType = QtWidgets.QComboBox(self.groupBox_4)
        self.algorithmType.setGeometry(QtCore.QRect(140, 20, 101, 31))
        self.algorithmType.setObjectName("algorithmType")
        self.algorithmType.addItem("")
        self.algorithmType.addItem("")
        self.algorithmType.addItem("")
        self.algorithmType.addItem("")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(20, 180, 101, 16))
        self.label_4.setObjectName("label_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_4)
        self.plainTextEdit.setGeometry(QtCore.QRect(140, 170, 104, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(470, 390, 361, 231))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_6.setGeometry(QtCore.QRect(330, 190, 31, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_5)
        self.tableWidget.setGeometry(QtCore.QRect(50, 60, 281, 161))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 20, 61, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_5.setGeometry(QtCore.QRect(270, 20, 61, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.displayAccuracy = QtWidgets.QTextBrowser(self.groupBox_5)
        self.displayAccuracy.setGeometry(QtCore.QRect(120, 20, 141, 31))
        self.displayAccuracy.setObjectName("displayAccuracy")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.load_data)
        self.pushButton_2.clicked.connect(MainWindow.load_train)
        self.pushButton_3.clicked.connect(MainWindow.getFeature)
        self.pushButton_4.clicked.connect(MainWindow.train_and_predict)
        self.pushButton_5.clicked.connect(MainWindow.predict)
        self.pushButton_6.clicked.connect(MainWindow.download_file)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "团簇光谱分类器"))
        self.groupBox.setTitle(_translate("MainWindow", "训练区"))
        self.pushButton_3.setText(_translate("MainWindow", "提取特征"))
        self.pushButton_2.setText(_translate("MainWindow", "导入训练样本"))
        self.displayDirname.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "测试区"))
        self.pushButton.setText(_translate("MainWindow", "导入测试样本"))
        self.groupBox_4.setTitle(_translate("MainWindow", "功能区"))
        self.skewness.setText(_translate("MainWindow", "偏度"))
        self.label_2.setText(_translate("MainWindow", "选择初始特征"))
        self.waveRate.setText(_translate("MainWindow", "波动率"))
        self.CV.setText(_translate("MainWindow", "峰谷比"))
        self.kurtosis.setText(_translate("MainWindow", "峰度"))
        self.peakPos.setText(_translate("MainWindow", "出峰位置"))
        self.label.setText(_translate("MainWindow", "选择分类算法"))
        self.algorithmType.setItemText(0, _translate("MainWindow", "KNN"))
        self.algorithmType.setItemText(1, _translate("MainWindow", "朴素贝叶斯"))
        self.algorithmType.setItemText(2, _translate("MainWindow", "决策树"))
        self.algorithmType.setItemText(3, _translate("MainWindow", "SVM"))
        self.label_4.setText(_translate("MainWindow", "参数k(默认为1)"))
        self.groupBox_5.setTitle(_translate("MainWindow", "结果区"))
        self.pushButton_6.setText(_translate("MainWindow", "导出"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "文件名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "预测分类"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "真实分类"))
        self.pushButton_4.setText(_translate("MainWindow", "训练模型"))
        self.pushButton_5.setText(_translate("MainWindow", "预测样本"))

