# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'software.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imagelabel = QtWidgets.QLabel(self.centralwidget)
        self.imagelabel.setGeometry(QtCore.QRect(460, 90, 281, 201))
        self.imagelabel.setFrameShape(QtWidgets.QFrame.Box)
        self.imagelabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.imagelabel.setText("")
        self.imagelabel.setObjectName("imagelabel")
        self.displayFname = QtWidgets.QTextBrowser(self.centralwidget)
        self.displayFname.setGeometry(QtCore.QRect(550, 30, 171, 31))
        self.displayFname.setObjectName("displayFname")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(460, 30, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 30, 81, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.displayDirname = QtWidgets.QTextBrowser(self.centralwidget)
        self.displayDirname.setGeometry(QtCore.QRect(140, 30, 121, 31))
        self.displayDirname.setObjectName("displayDirname")
        self.imagelabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.imagelabel_2.setGeometry(QtCore.QRect(50, 90, 281, 201))
        self.imagelabel_2.setFrameShape(QtWidgets.QFrame.Box)
        self.imagelabel_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.imagelabel_2.setText("")
        self.imagelabel_2.setObjectName("imagelabel_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 30, 61, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.algorithmType = QtWidgets.QComboBox(self.centralwidget)
        self.algorithmType.setGeometry(QtCore.QRect(170, 360, 81, 31))
        self.algorithmType.setObjectName("algorithmType")
        self.algorithmType.addItem("")
        self.algorithmType.addItem("")
        self.algorithmType.addItem("")
        self.algorithmType.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 360, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 410, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(460, 360, 61, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.peakPos = QtWidgets.QCheckBox(self.centralwidget)
        self.peakPos.setGeometry(QtCore.QRect(170, 420, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.peakPos.setFont(font)
        self.peakPos.setObjectName("peakPos")
        self.CV = QtWidgets.QCheckBox(self.centralwidget)
        self.CV.setGeometry(QtCore.QRect(170, 450, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.CV.setFont(font)
        self.CV.setObjectName("CV")
        self.kurtosis = QtWidgets.QCheckBox(self.centralwidget)
        self.kurtosis.setGeometry(QtCore.QRect(170, 540, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.kurtosis.setFont(font)
        self.kurtosis.setObjectName("kurtosis")
        self.waveRate = QtWidgets.QCheckBox(self.centralwidget)
        self.waveRate.setGeometry(QtCore.QRect(170, 480, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.waveRate.setFont(font)
        self.waveRate.setObjectName("waveRate")
        self.skewness = QtWidgets.QCheckBox(self.centralwidget)
        self.skewness.setGeometry(QtCore.QRect(170, 510, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.skewness.setFont(font)
        self.skewness.setObjectName("skewness")
        self.displayAccuracy = QtWidgets.QTextBrowser(self.centralwidget)
        self.displayAccuracy.setGeometry(QtCore.QRect(530, 360, 141, 31))
        self.displayAccuracy.setObjectName("displayAccuracy")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(680, 360, 61, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(460, 400, 281, 161))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(750, 530, 31, 31))
        self.pushButton_6.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:/1考研/Button_Download.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setObjectName("pushButton_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.load_data)
        self.pushButton_2.clicked.connect(MainWindow.load_train)
        self.pushButton_3.clicked.connect(MainWindow.getFeature)
        self.pushButton_4.clicked.connect(MainWindow.train_and_predict)
        self.pushButton_5.clicked.connect(MainWindow.predict)
        self.pushButton_6.clicked.connect(MainWindow.download_file)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "导入测试样本"))
        self.pushButton_2.setText(_translate("MainWindow", "导入训练样本"))
        self.displayDirname.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "提取特征"))
        self.algorithmType.setItemText(0, _translate("MainWindow", "KNN"))
        self.algorithmType.setItemText(1, _translate("MainWindow", "朴素贝叶斯"))
        self.algorithmType.setItemText(2, _translate("MainWindow", "决策树"))
        self.algorithmType.setItemText(3, _translate("MainWindow", "SVM"))
        self.label.setText(_translate("MainWindow", "选择分类算法："))
        self.label_2.setText(_translate("MainWindow", "选择初始特征："))
        self.pushButton_4.setText(_translate("MainWindow", "训练模型"))
        self.peakPos.setText(_translate("MainWindow", "出峰位置"))
        self.CV.setText(_translate("MainWindow", "峰谷比"))
        self.kurtosis.setText(_translate("MainWindow", "峰度"))
        self.waveRate.setText(_translate("MainWindow", "波动率"))
        self.skewness.setText(_translate("MainWindow", "偏度"))
        self.pushButton_5.setText(_translate("MainWindow", "预测样本"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "文件名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "预测分类"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "真实分类"))
